meta-intel-bsp: Skip parsing linux-intel-private recipes if not used
linux-intel-private recipes uses kernel sources from a private repository
(Intel-Innersource) reachable only from Intel network. If a user has no
access but it doesn't use this recipe, bitbake will parse the recipe and
should get no error because it doesn't try to fetch the sources.

BUT, starting with commit c81119d8cd ("linux-intel-private: Add variable
to set the branch in local.conf"), the linux-intel-private recipe was made
more generic and compiles latest sources from the branch (AUTOREV).

In this case, when there is no SHA number defined in the recipe, bitbake
must query the repository to determine the latest revision during the parsing
step even if the recipe is not used in the build. If the repository is
inaccessible bitbake fails immediately because it can't determine the revision.

That's why a user with no access to the private repository will get error
even if it use another package for virtual/kernel when AUTOREV is used:

bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue],
	expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError:
	failed with exit code 128, output:
remote: Repository not found.
fatal: repository 'https://github.com/intel-innersource/networking.wireless.transport.rdk.bts-kernel.git/' not found

Cover this case by adding linux-intel-private recipes on BBMASK to skip
parsing recipes when PREFERRED_PROVIDER_virtual/kernel is set to another
linux recipe.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>