ltp: Backport patch to fix cve-2015-3290 testcase
After upgrading to GCC v13.4 from v13.3, cve-2015-3290.c testcase
fail to compile even if -fomit-frame-pointer flag is used:
      cve-2015-3290.c:397:1: error: bp cannot be used in 'asm' here

Backport patch from v20250530 to disable AVX for x86_64:

When the input compiler enables AVX, stack realignment requirements
causes gcc to fail to omit %rbp use, due to which the test fails to
clobber %rbp in inline asm.  Disable AVX to build the test on x86_64 so
that the test continues working.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>