wic: Fix altkernel detection on AXXIA customized source plugin
commit e199602fb9 ("wic: Fix AXXIA customized source plugin") add
a check for any alternative kernel in IMAGE_INSTALL variable to
ensure the choosen image installs it. Fix this check by searching
not only for altkernel package, but for any package starting with
altkernel*. Without this, wic tool used standalone will complain
abount not finding any alternative kernel:

"altkernel" not in get_bitbake_var("IMAGE_INSTALL"):
TypeError: argument of type 'NoneType' is not iterable

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>